# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SketchMockups.com
email: james@magicsketch.io
author: sketchmockups
description: 'The complete directory of Sketch perspective mockups for your presentation'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sketchmockups.com" # the base hostname & protocol for your site
twitter_username: sketchmockups
github_username:  jamztang
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'README.md', '_scripts']
share:
    image: /images/share-facebook.png
    twitter_image: /images/share-twitter.png
    tweet_text: ''

settings:
  development:
    url: "http://localhost:4000"
  staging:
    url: "https://strawberry.sketchmockups.com"
    analytics:
      ga: 'UA-97236949-2'
      mixpanel: ''
  production:
    url: "https://sketchmockups.com"
    analytics:
      ga: 'UA-97236949-1'
      mixpanel: ''

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"